In [1]:
import pandas as pd

In [2]:
data = pd.read_hdf('data_feat.h5', 'table')

In [3]:
data.head().T

,1497465,1497466,1497467,1497468,1497469
date_block_num,4.000000,4.000000,4.0,4.000000,4.000000
shop_id,2.000000,2.000000,2.0,2.000000,2.000000
item_id,27.000000,28.000000,29.0,30.000000,31.000000
item_cnt_month,0.000000,0.000000,0.0,0.000000,0.000000
shop_category,4.000000,4.000000,4.0,4.000000,4.000000
shop_city,0.000000,0.000000,0.0,0.000000,0.000000
item_category_id,19.000000,30.000000,23.0,40.000000,37.000000
name2,76.000000,107.000000,123.0,4.000000,4.000000
name3,42.000000,42.000000,42.0,42.000000,562.000000
subtype_code,10.000000,55.000000,16.0,4.000000,1.000000
type_code,3.000000,3.000000,3.0,5.000000,5.000000
item_cnt_month_lag_1,0.000000,0.000000,NaN,0.000000,1.000000
item_cnt_month_lag_2,0.000000,0.000000,NaN,1.000000,1.000000
item_cnt_month_lag_3,0.000000,0.000000,NaN,0.000000,4.000000
date_avg_item_cnt_lag_1,0.286865,0.286865,NaN,0.286865,0.286865
date_item_avg_item_cnt_lag_1,0.021744,0.130493,NaN,2.826172,1.260742
date_item_avg_item_cnt_lag_2,0.086975,0.152222,NaN,11.046875,4.781250
date_item_avg_item_cnt_lag_3,0.065247,0.173950,NaN,18.734375,13.648438
date_shop_avg_item_cnt_lag_1,0.071838,0.071838,NaN,0.071838,0.071838
date_shop_avg_item_cnt_lag_2,0.091064,0.091064,NaN,0.091064,0.091064
date_shop_avg_item_cnt_lag_3,0.059875,0.059875,NaN,0.059875,0.059875
date_shop_item_avg_item_cnt_lag_1,0.000000,0.000000,NaN,0.000000,1.000000
date_shop_item_avg_item_cnt_lag_2,0.000000,0.000000,NaN,1.000000,1.000000
date_shop_item_avg_item_cnt_lag_3,0.000000,0.000000,NaN,0.000000,4.000000
date_shop_subtype_avg_item_cnt_lag_1_x,0.449463,0.387207,NaN,0.018585,0.035919
date_shop_subtype_avg_item_cnt_lag_1_y,0.449463,0.387207,NaN,0.018585,0.035919
date_city_avg_item_cnt_lag_1,0.071838,0.071838,NaN,0.071838,0.071838
date_item_city_avg_item_cnt_lag_1,0.000000,0.000000,NaN,0.000000,1.000000
delta_price_lag,0.367676,0.256348,0.0,0.212402,0.191040
delta_revenue_lag_1,37326.816406,37326.816406,NaN,37326.816406,37326.816406
month,4.000000,4.000000,4.0,4.000000,4.000000
days,31.000000,31.000000,31.0,31.000000,31.000000
item_shop_first_sale,4.000000,4.000000,4.0,3.000000,3.000000
item_first_sale,4.000000,4.000000,4.0,3.000000,3.000000

In [4]:
missing_val_count_by_column = (data.isnull().sum())

In [5]:
missing_val_count_by_column

date_block_num                                  0
shop_id                                         0
item_id                                         0
item_cnt_month                                  0
shop_category                                   0
shop_city                                       0
item_category_id                                0
name2                                           0
name3                                           0
subtype_code                                    0
type_code                                       0
item_cnt_month_lag_1                      1957843
item_cnt_month_lag_2                      2252408
item_cnt_month_lag_3                      2539771
date_avg_item_cnt_lag_1                   1957843
date_item_avg_item_cnt_lag_1              1957843
date_item_avg_item_cnt_lag_2              2252408
date_item_avg_item_cnt_lag_3              2539771
date_shop_avg_item_cnt_lag_1              1957843
date_shop_avg_item_cnt_lag_2              2252408
date_shop_avg_item_cnt_lag_3              2539771
date_shop_item_avg_item_cnt_lag_1         1957843
date_shop_item_avg_item_cnt_lag_2         2252408
date_shop_item_avg_item_cnt_lag_3         2539771
date_shop_subtype_avg_item_cnt_lag_1_x    1957843
date_shop_subtype_avg_item_cnt_lag_1_y    1957843
date_city_avg_item_cnt_lag_1              1957843
date_item_city_avg_item_cnt_lag_1         1957843
delta_price_lag                                 0
delta_revenue_lag_1                       1957843
month                                           0
days                                            0
item_shop_first_sale                            0
item_first_sale                                 0
dtype: int64

In [6]:
data.nunique()

date_block_num                               31
shop_id                                      55
item_id                                   20883
item_cnt_month                              436
shop_category                                 5
shop_city                                    31
item_category_id                             82
name2                                       166
name3                                      1583
subtype_code                                 65
type_code                                    10
item_cnt_month_lag_1                        427
item_cnt_month_lag_2                        418
item_cnt_month_lag_3                        415
date_avg_item_cnt_lag_1                      30
date_item_avg_item_cnt_lag_1               2530
date_item_avg_item_cnt_lag_2               2523
date_item_avg_item_cnt_lag_3               2510
date_shop_avg_item_cnt_lag_1               1121
date_shop_avg_item_cnt_lag_2               1113
date_shop_avg_item_cnt_lag_3               1114
date_shop_item_avg_item_cnt_lag_1           427
date_shop_item_avg_item_cnt_lag_2           418
date_shop_item_avg_item_cnt_lag_3           415
date_shop_subtype_avg_item_cnt_lag_1_x     7125
date_shop_subtype_avg_item_cnt_lag_1_y     7125
date_city_avg_item_cnt_lag_1                757
date_item_city_avg_item_cnt_lag_1          1252
delta_price_lag                           17123
delta_revenue_lag_1                        1429
month                                        12
days                                          3
item_shop_first_sale                         35
item_first_sale                              35
dtype: int64

In [4]:
X_train = data[data.date_block_num < 33].drop(['item_cnt_month'], axis=1).fillna(-1)
Y_train = data[data.date_block_num < 33]['item_cnt_month']
X_valid = data[data.date_block_num == 33].drop(['item_cnt_month'], axis=1).fillna(-1)
Y_valid = data[data.date_block_num == 33]['item_cnt_month']
X_test = data[data.date_block_num == 34].drop(['item_cnt_month'], axis=1).fillna(-1)

In [5]:
Y_train = Y_train.clip(0, 20)
Y_valid = Y_valid.clip(0, 20)

In [6]:
import time
ts = time.time()

from sklearn import linear_model
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

y_pred_train = regr.predict(X_train).clip(0, 20)
y_pred_valid = regr.predict(X_valid).clip(0, 20)

time.time() - ts

16.924362182617188

In [7]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rmse_train = sqrt(mean_squared_error(Y_train, y_pred_train))
rmse_valid = sqrt(mean_squared_error(Y_valid, y_pred_valid))

print("RMSE for train: {}, RMSE for valid: {}".format(rmse_train, rmse_valid))

RMSE for train: 1.0361586989064262, RMSE for valid: 1.0355244683396088

In [9]:
# use only numeric features

cats_cols = ['date_block_num', 'shop_id', 'item_id', 'shop_category', 'shop_city', 'item_category_id', 'name2', 'name3', 'subtype_code', 'type_code', 'month', 'days']
X_train = data[data.date_block_num < 33].drop(['item_cnt_month'] + cats_cols, axis=1).fillna(-1)
Y_train = data[data.date_block_num < 33]['item_cnt_month']
X_valid = data[data.date_block_num == 33].drop(['item_cnt_month'] + cats_cols, axis=1).fillna(-1)
Y_valid = data[data.date_block_num == 33]['item_cnt_month']

X_test = data[data.date_block_num == 34].drop(['item_cnt_month'] + cats_cols, axis=1).fillna(-1)

Y_train = Y_train.clip(0, 20)
Y_valid = Y_valid.clip(0, 20)

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

y_pred_train = regr.predict(X_train).clip(0, 20)
y_pred_valid = regr.predict(X_valid).clip(0, 20)


rmse_train = sqrt(mean_squared_error(Y_train, y_pred_train))
rmse_valid = sqrt(mean_squared_error(Y_valid, y_pred_valid))

print("RMSE for train: {}, RMSE for valid: {}".format(rmse_train, rmse_valid))

RMSE for train: 1.0398918799905654, RMSE for valid: 1.0330248500423664

In [10]:
# let's standardize the data

from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_valid = scaler.transform(X_valid)

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

y_pred_train = regr.predict(X_train).clip(0, 20)
y_pred_valid = regr.predict(X_valid).clip(0, 20)


rmse_train = sqrt(mean_squared_error(Y_train, y_pred_train))
rmse_valid = sqrt(mean_squared_error(Y_valid, y_pred_valid))

print("RMSE for train: {}, RMSE for valid: {}".format(rmse_train, rmse_valid))

RMSE for train: 1.039902311835593, RMSE for valid: 1.0330217919834546

In [14]:
data.shape

(9630539, 34)